services:
  minix-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minix-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
