# Server Configuration
server:
  port: 8080

# Logging
logging:
  level:
    com:
      example:
        minix: DEBUG

timeline:
  max-length: 50


event-publisher:
  threadpool:
    core-size: 5
    max-size: 10
    ttl-in-sec: 10
    queue-capacity: 100

auth-filter:
  excluded-paths:
    - "/v3/api-docs"
    - "/swagger-ui"